name:                agda2llvm
version:             0.1.0.0
github:              "jochembroekhoff/agda2llvm"
#license:             BSD3
author:              "Jochem Broekhoff"
maintainer:          "J.H.Broekhoff@student.tudelft.nl"
copyright:           "2022 Jochem Broekhoff"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jochembroekhoff/agda2llvm#readme>

dependencies:
- base >= 4.7 && < 5
- Agda >= 2.6.2.1 && < 2.6.3
- deepseq >= 1.4.5
- ghc
- filepath >= 1.4 && < 2
- containers
- directory
- mtl >= 2.2.2 && < 3
- utf8-string
- bytestring
- crc >= 0.1.1.1

data-dir: data
data-files:
- Agda.ll
- header.ll

library:
  source-dirs: src

executables:
  agda2llvm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - agda2llvm

tests:
  agda2llvm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - agda2llvm

default-extensions:
  - BlockArguments
  - DeriveAnyClass
  - DeriveGeneric
  - FlexibleInstances
  - LambdaCase
  - MultiParamTypeClasses
  - ScopedTypeVariables
  - TupleSections
